trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: 'Use Python 3.8'
  - script: pip install checkov
    displayName: 'Install Checkov'
  - script: checkov -d <directory> --bc-api-key 68570819-c42e-466b-83f9-f6e52c1386b5 ::9cY0/JybRHT6WNHBAe4OeYGCXB8= --repo-id abheemarao/terragoat> --branch master
    displayName: 'Scan with Prisma CLoud'
    env:
    PRISMA_API_URL: https://api4.prismacloud.io