- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d terragoat --bc-api-key  --repo-id abheemarao/terragoat --branch master
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: https://api4.prismacloud.io
