jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: 'Use Python 3.8'
  - script: pip install checkov
    displayName: 'Install Checkov'
  - script: checkov -d <directory> --bc-api-key --repo-id abheemarao/terragoat> --branch master
    displayName: 'Scan with Prisma CLoud'
    env:
      PRISMA_API_URL: https://api4.prismacloud.io